eureka:
   instance:
     instance-id: onlyEurekaServer
     ip-address: 127.0.0.1
     lease-expiration-duration-in-seconds: 90
     lease-renewal-interval-in-seconds: 30
   client:
     register-with-eureka: false
     fetch-registry: false
     service-url:
       defaultZone: http://localhost:8888/eureka/
   server:
     renewalPercentThreshold: 0.8
